# Generated by Django 4.2.27 on 2025-12-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproduct',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='videoproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videoproduct',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='videoproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videoproduct',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='videoproduct',
            name='product_url',
        ),
        migrations.RemoveField(
            model_name='videoproduct',
            name='updated_at',
        ),
    ]
