# Generated by Django 4.2.27 on 2025-12-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_videoproduct_actual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
