# Generated by Django 4.2.27 on 2025-12-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videoproduct_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=100),
        ),
    ]
