# Generated by Django 4.2.27 on 2026-03-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
